spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ejournal?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000
